expname: tas2Rg_amip_extended_HadGEM
device: gpu
seed_list: [42]
fig_dpi: 300
datamaker:
    datafolder: LargeEnsemble/
    models:
        - HadGEM3-GC31-LL
    data_periods:
        - _amip-piForcing_1871-2020
    detrend: false
    n_train_val_test: [0, 0, 1]
    input_var: tas
    label_var: R
    input_mask: false
    label_mask: false
    map_output: false
    date_bounds: ['1871-01-01', '2020-12-30']
    anomalies: years
    anomaly_dates: ['1980-01-01', '1999-12-30']
    batch_size: 32
    args: {}